# Generated by Django 4.2.5 on 2023-11-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0015_alter_user_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalles',
            field=models.CharField(max_length=300),
        ),
    ]
