# Generated by Django 4.2.5 on 2023-11-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0016_alter_producto_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='productos',
            field=models.ManyToManyField(to='e_commerce_app.producto'),
        ),
    ]
