# Generated by Django 4.2.5 on 2023-11-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0017_user_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='productos',
            new_name='favoritos',
        ),
    ]
