# Generated by Django 4.2.5 on 2023-11-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0018_rename_productos_user_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favoritos',
            field=models.ManyToManyField(blank=True, to='e_commerce_app.producto'),
        ),
    ]
